### ISSUE TITLE
" ghc --make FileServer.hs" encounter error,how to fix it?

### ISSUE THREAD

**Issue by luckypoem** [snoyberg/file-server-demo#2]
hi.

root@AR:/usr/local/snoyberg-file-server-demo# ghc --make FileServer.hs
[1 of 1] Compiling Main             ( FileServer.hs, FileServer.o )

FileServer.hs:39:1: error:
    Failed to load interface for ‘Text.Hamlet’
    Use -v to see a list of the files searched for.
root@AR:/usr/local/snoyberg-file-server-demo#

thank u

**Comment by snoyberg** [comment]
It's due to missing libraries. The code is intended to be run with [Stack](https://haskell-lang.org/get-started), which will automatically install dependencies. Can you try with `stack FileServer.hs` instead?

**Comment by luckypoem** [comment]
root@AR:/usr/local/snoyberg-file-server-demo# stack FileServer.hs
Downloaded lts-6.11 build plan.    
Plan construction failed.
root@AR:/usr/local/snoyberg-file-server-demo# 

so how to fix it?

**Comment by snoyberg** [comment]
Hmm, that's curious. Could you tell me the output of the following commands?

```
$ stack --version
$ stack --resolver lts-6.11 --install-ghc build shakespeare wai-app-static wai-extra warp --verbose
$ stack --resolver lts-6.11 --verbose runghc FileServer.hs
```

Also, just as a complete guess, does the following work?

```
$ stack --resolver lts-7.9 --install-ghc runghc --package shakespeare --package wai-app-static --package wai-extra --package warp FileServer.hs
```

**Comment by luckypoem** [comment]
root@AR:/usr/local/snoyberg-file-server-demo# stack --resolver lts-7.9 --install-ghc runghc --package shakespeare --package wai-app-static --package wai-extra --package warp FileServer.hs
Run from outside a project, using implicit global project config
Using resolver: lts-7.9 specified on command line

While constructing the build plan, the following exceptions were encountered:

In the dependencies for deepseq-1.3.0.2:
    base-4.9.0.0 must match >=4.3 && <4.8 (latest applicable is 4.7.0.2)

Plan construction failed.
root@AR:/usr/local/snoyberg-file-server-demo# stack --version
Version 1.2.0, Git revision 241cd07d576d9c0c0e712e83d947e3dd64541c42 (4054 commits) i386 hpack-0.14.0
root@AR:/usr/local/snoyberg-file-server-demo#

**Comment by luckypoem** [comment]
the result of running "stack --resolver lts-6.11 --install-ghc build shakespeare wai-app-static wai-extra warp --verbose":

...
2016-11-23 08:40:49.875277: [error] 
While constructing the build plan, the following exceptions were encountered:

In the dependencies for deepseq-1.3.0.2:
    base-4.8.2.0 must match >=4.3 && <4.8 (latest applicable is 4.7.0.2)

@(Stack/Build/ConstructPlan.hs:195:13)
Plan construction failed.
root@AR:/usr/local/snoyberg-file-server-demo#

**Comment by snoyberg** [comment]
Can you try adding `--no-system-ghc` to these commands? And do you by any chance have a GHC installed via a means besides Stack, and what is it?

**Comment by luckypoem** [comment]
root@AR:/usr/local/snoyberg-file-server-demo# stack FileServer.hs --no-system-ghc
Plan construction failed.
root@AR:/usr/local/snoyberg-file-server-demo#

root@AR:/usr/local/snoyberg-file-server-demo# which ghc
/usr/local/haskell/ghc-8.0.1-i386/bin/ghc
root@AR:/usr/local/snoyberg-file-server-demo# 

i installed the ghc thru haskell platform.is this the culprit?

**Comment by snoyberg** [comment]
Yes, the platform is almost certainly the culprit. We're changing the default in Stack to avoid system GHCs because of problems like this. I meant to try:

```
$ stack --resolver lts-7.9 --install-ghc --no-system-ghc runghc --package shakespeare --package wai-app-static --package wai-extra --package warp FileServer.hs
```

This will instruct Stack to not use the Platform-installed GHC at all.

**Comment by luckypoem** [comment]
root@AR:/usr/local/snoyberg-file-server-demo# stack --resolver lts-7.9 --install-ghc --no-system-ghc runghc --package shakespeare --package wai-app-static --package wai-extra --package warp FileServer.hs
Run from outside a project, using implicit global project config
Using resolver: lts-7.9 specified on command line
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Downloaded ghc-8.0.1.                                      
Installing GHC ...                                                     
Installed GHC.    

While constructing the build plan, the following exceptions were encountered:

In the dependencies for deepseq-1.3.0.2:
    base-4.9.0.0 must match >=4.3 && <4.8 (latest applicable is 4.7.0.2)

Plan construction failed.
root@AR:/usr/local/snoyberg-file-server-demo#

**Comment by luckypoem** [comment]
still doesn't work

**Comment by snoyberg** [comment]
I'm sorry, I can't explain this behavior and can't reproduce it. The snapshot in question doesn't use deepseq-1.3.0.2 (it uses version 1.4.2.0). The only last thing I can think of is that you somehow have some cached files that have been corrupted, but I can't think of a way that would happen. `rm -rf ~/.stack` may help.

Last set of questions I can think of:

* What OS are you on?
* I see you have a 32-bit Stack, is your OS actually 32-bit?
* Where did you get the Stack executable from?

**Comment by luckypoem** [comment]
root@AR:/usr/local/snoyberg-file-server-demo#  cat /etc/issue.net
Debian GNU/Linux 7
root@AR:/usr/local/snoyberg-file-server-demo# uname -a
Linux AR 2.6.32-042stab117.14 #1 SMP Tue Aug 30 17:12:57 MSK 2016 i686 GNU/Linux
root@AR:/usr/local/snoyberg-file-server-demo#

i installed stack thru "curl -sSL https://get.haskellstack.org/ | sh"

**Comment by Blaisorblade** [comment]
> Run from outside a project, using implicit global project config

Already established what that says?

**Comment by snoyberg** [comment]
That's a good question. @luckypoem what does `cat ~/.stack/global-project/stack.yaml` result in? And how about `stack --resolver lts-7.9 --install-ghc --no-system-ghc build warp`?

**Comment by luckypoem** [comment]
hi.

root@AR:/usr/local/snoyberg-file-server-demo# stack --resolver lts-7.9 --install-ghc --no-system-ghc build warp
Run from outside a project, using implicit global project config
Using resolver: lts-7.9 specified on command line

While constructing the build plan, the following exceptions were encountered:

In the dependencies for deepseq-1.3.0.2:
    base-4.9.0.0 must match >=4.3 && <4.8 (latest applicable is 4.7.0.2)

Plan construction failed.
root@AR:/usr/local/snoyberg-file-server-demo#

still not ok

**Comment by Blaisorblade** [comment]
Again, @luckypoem, what about the global stack.yaml?

**Comment by luckypoem** [comment]
@Blaisorblade 

root@AR:~# cat ~/.stack/global-project/stack.yaml
# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/root/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
extra-deps: [citeproc-hs-0.3.10]
extra-deps: [strict-concurrency-0.2.4.1]
extra-deps: [base-4.5.1.0]
extra-deps: [deepseq-1.3.0.2]
resolver: lts-6.8
flags: {}
extra-package-dbs: []
packages: []
root@AR:~#

i need to change deepseq-1.3.0.2 to be deepseq-1.4.2.0?

**Comment by Blaisorblade** [comment]
I think you want to drop, at least, the lines mentioning deepseq and base. I can imagine why those deps arose, but overriding dependencies in the global project is a recipe for the trouble you're seeing. We might want stack to give a warning?
Keeping them with a different resolver is also an interesting choice...

**Comment by luckypoem** [comment]
hi.

actually i didn't drop the lines mentioning deepseq and base,i just modified their versions.but i still enconter error below.the application cannot be launched.how to fix it?

root@AR:/usr/local/snoyberg-file-server-demo# stack FileServer.hs
Progress: 0/79
Progress: 38/79
Progress: 54/79
Progress: 67/79
Progress: 68/79
Completed 79 action(s).
Launching application

^C
root@AR:/usr/local/snoyberg-file-server-demo# 
root@AR:/usr/local/snoyberg-file-server-demo# stack FileServer.hs
Launching application

**Comment by snoyberg** [comment]
The server is running. You can now visit http://localhost:8080

**Comment by luckypoem** [comment]
oh,i see.how to modify 8080 to other port?

**Comment by snoyberg** [comment]
Edit the code. There are lots of comments explaining what's going on, as well as the README.md file.

If you don't mind, let's close out this issue, as the problem has been resolved.

**Comment by luckypoem** [comment]
yes,i see it,just modify FileServer.hs
